version: '3.3'

services:
    app:
        build: .
        ports:
            - 8080:8080
        volumes:
            - .:/home/lstu
    db:
        image: mariadb:10.2
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=lstu